<?php
$sstr=array(
':-*',
':*',
'=))',
':))',
':-)',
':)',
':((',
';-)',
';)',
':-P',
':-p',
':P',
':p',
':b',
':(',
':-(',
':-D',
':D',
':-d',
':d',
':-O',
':O',
':-o',
':o',
'bodem',
'bokong',
'bubuk',
'ckaka',
'dongkol',
'download',
'goodluck',
':he',
'help',
'huahaha',
'huh',
'mumet',
'minum',
'ngopi',
'nguli',
'pentung',
'rok',
'salaman',
'sip',
'udut',
);
$simg=array(
'<img src="/tema/sm/1.gif" alt=":-*"/>',
'<img src="/tema/sm/1.gif" alt=":*"/>',
'<img src="/tema/sm/2.gif" alt="=))"/>',
'<img src="/tema/sm/3.gif" alt=":))"/>',
'<img src="/tema/sm/4.gif" alt=":-)"/>',
'<img src="/tema/sm/4.gif" alt=":)"/>',
'<img src="/tema/sm/5.gif" alt=":(("/>',
'<img src="/tema/sm/6.gif" alt=";-)"/>',
'<img src="/tema/sm/6.gif" alt=";)"/>',
'<img src="/tema/sm/7.gif" alt=":-P"/>',
'<img src="/tema/sm/7.gif" alt=":-p"/>',
'<img src="/tema/sm/7.gif" alt=":P"/>',
'<img src="/tema/sm/7.gif" alt=":p"/>',
'<img src="/tema/sm/7.gif" alt=":b"/>',
'<img src="/tema/sm/8.gif" alt=":("/>',
'<img src="/tema/sm/8.gif" alt=":-("/>',
'<img src="/tema/sm/9.gif" alt=":-D"/>',
'<img src="/tema/sm/9.gif" alt=":D"/>',
'<img src="/tema/sm/9.gif" alt=":-d"/>',
'<img src="/tema/sm/9.gif" alt=":d"/>',
'<img src="/tema/sm/10.gif" alt=":-O"/>',
'<img src="/tema/sm/10.gif" alt=":O"/>',
'<img src="/tema/sm/10.gif" alt=":-o"/>',
'<img src="/tema/sm/10.gif" alt=":o"/>',
'<img src="http://seupang.tk/shoutbox/sm/bodem.gif" alt="bodem"/>',
'<img src="http://seupang.tk/shoutbox/sm/bokong.gif" alt="bokong"/>',
'<img src="http://seupang.tk/shoutbox/sm/bubuk.gif" alt="bubuk"/>',
'<img src="http://seupang.tk/shoutbox/sm/ckaka.gif" alt="ckaka"/>',
'<img src="http://seupang.tk/shoutbox/sm/dongkol.gif" alt="dongkol"/>',
'<img src="http://seupang.tk/shoutbox/sm/download.gif" alt="download"/>',
'<img src="http://seupang.tk/shoutbox/sm/goodluck.gif" alt="goodluck"/>',
'<img src="http://seupang.tk/shoutbox/sm/he.gif" alt=":he"/>',
'<img src="http://seupang.tk/shoutbox/sm/help.gif" alt="help"/>',
'<img src="http://seupang.tk/shoutbox/sm/huahaha.gif" alt="huahaha"/>',
'<img src="http://seupang.tk/shoutbox/sm/huh.gif" alt="huh"/>',
'<img src="http://seupang.tk/shoutbox/sm/mumet.gif" alt="mumet"/>',
'<img src="http://seupang.tk/shoutbox/sm/minum.gif" alt="minum"/>',
'<img src="http://seupang.tk/shoutbox/sm/ngopi.gif" alt="ngopi"/>',
'<img src="http://seupang.tk/shoutbox/sm/nguli.gif" alt="nguli"/>',
'<img src="http://seupang.tk/shoutbox/sm/pentung.gif" alt="pentung"/>',
'<img src="http://seupang.tk/shoutbox/sm/rok.gif" alt="rok"/>',
'<img src="http://seupang.tk/shoutbox/sm/salaman.gif" alt="salaman"/>',
'<img src="http://seupang.tk/shoutbox/sm/sip.gif" alt="sip"/>',
'<img src="http://seupang.tk/shoutbox/sm/udut.gif" alt="udut"/>',
);
?>
